[book]
authors = ["the skiftOS Develpers"]
language = "en"
multilingual = false
src = "."
title = "SkiftOS Handbook"

[output.html]
default-theme = "skift-dark"
preferred-dark-theme = "skift-dark"
git-repository-url = "https://codeberg.org/skift/os"
edit-url-template = "https://codeberg.org/skift/os/edit/main/doc/{path}"
