name: Build
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Toolchains
        run: brew install llvm python git ninja &&
             python3 -m ensurepip && git clone https://github.com/cute-engineering/osdk && sudo python3 -m pip install -e osdk/

      - name: Build Kernel (x86_64)
        run: osdk b --target=kernel-x86_64

      - name: Build EFI (x86_64)
        run: osdk b --target=efi-x86_64

      - name: Build Host
        run: osdk b

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Toolchains
        run: sudo apt-get install clang lld llvm python3 git ninja-build &&
             git clone https://github.com/cute-engineering/osdk && sudo pip install -e osdk/

      - name: Build Kernel (x86_64)
        run: osdk b --target=kernel-x86_64

      - name: Build EFI (x86_64)
        run: osdk b --target=efi-x86_64

      - name: Build Host
        run: osdk b
